### ISSUE TITLE
download as ebook

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [JulienPalard/mailman-fetch#1]
came acroos this repo while searching, could you add a download archives as ebooks option? like more readable 

https://github.com/Abdur-rahmaanJ/pipermail2ebook i tried but it became bit of a mess

**Comment by JulienPalard** [comment]
Hi,

That could be nice, and there may exist a way to do it painlessly. Maybe by using [MHonArc](https://www.mhonarc.org) and making it generate a single HTML page via its [layout configuration](https://www.mhonarc.org/MHonArc/doc/layout.html), didn't tried it though.

The single HTML page could include anchors to jump from a mail to another by thread/date and back to the thread list. This page could be transformed to PDF using [WeasyPrint](https://github.com/Kozea/WeasyPrint/).

If someone want to try it, PR would be appreciated, but I don't think I'll try it myself.

**Comment by Abdur-rahmaanJ** [comment]
pining down as side project, thanks for hints !
